# Generated by Django 5.2.4 on 2025-07-06 17:41

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=255)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=18, default=Decimal("0.0"), max_digits=30
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "indexes": [
                    models.Index(fields=["label"], name="wallets_wal_label_e47896_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", Decimal("0.0"))),
                        name="wallet_balance_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "txid",
                    models.CharField(
                        help_text="Unique transaction identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=18,
                        help_text="Can be negative. Up to 18 digits precision.",
                        max_digits=30,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet"], name="wallets_tra_wallet__757bec_idx"
                    ),
                    models.Index(fields=["txid"], name="wallets_tra_txid_8d45b1_idx"),
                ],
            },
        ),
    ]
